# Generated by Django 3.0.6 on 2020-05-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name: ', max_length=128)),
                ('phone', models.IntegerField(help_text='Phone Number: ')),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(help_text='Address: ', max_length=200)),
                ('photo', models.ImageField(help_text='Upload image: ', upload_to='')),
                ('description', models.CharField(help_text='Comments: ', max_length=500)),
            ],
        ),
    ]
