# Generated by Django 3.0.6 on 2020-05-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200523_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='pool',
            field=models.IntegerField(),
        ),
    ]
