# Generated by Django 3.0.6 on 2020-05-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20200523_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent'), ('Lease', 'Lease')], default=2, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('Lagos', 'Lagos'), ('Abuja', 'Abuja'), ('Rivers', 'Rivers'), ('Anambra', 'Anambra'), ('Plateau', 'Plateau'), ('Ekiti', 'Ekiti'), ('0gun', 'Ogun'), ('Delta', 'Delta'), ('Kano', 'Kano'), ('Enugu', 'Enugu'), ('Kaduna', 'Kaduna'), ('Katsina', 'Katsina'), ('Akwa Ibom', 'Akwa Ibom'), ('Cross River', 'Cross River'), ('Edo', 'Edo'), ('Imo', 'Imo'), ('Bayelsa', 'Bayelsa')], max_length=15),
        ),
        migrations.AlterField(
            model_name='listing',
            name='zipcode',
            field=models.CharField(max_length=7),
        ),
    ]
